# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Stick to a specific version to prevent unexpected changes
    rev: v0.4.10
    hooks:
    # Run the linter
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    # Run theformatter
    -   id: ruff-format

